version: '3'

services:
  spring-app:
    image: mohyehia99/spring-boot-testing:0.0.5
    ports:
      - "9090:9090"
    depends_on:
      - mongo-db
  mongo-db:
    container_name: mongo-db
    image: mongo:7.0.1
    restart: unless-stopped
    ports:
      - "27017:27017"
    expose:
      - '27017'
    volumes:
      - ./volumes/mongo:/data/db
