name: Java CI with Maven and JUnit 5

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and run tests
        run: mvn clean test

  coverage:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install dependencies
        run: mvn -B org.apache.maven.plugins:maven-dependency-plugin:3.1.2:get -Dartifact=org.jacoco:jacoco-maven-plugin:0.8.7 -DrepoUrl=https://repo.maven.apache.org/maven2/

      - name: Run JaCoCo for test coverage
        run: mvn jacoco:prepare-agent test jacoco:report

      - name: Check coverage threshold
        run: |
          COVERAGE=$(grep -Po "TOTAL.*?(\d+\.\d+)" target/site/jacoco/index.html | awk '{print $NF}')
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Error: Coverage is below 80%."
            exit 1
          fi

      - name: Upload coverage results
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: target/site/jacoco
