name: Java CI with Maven and JUnit 5

on:
  pull_request:
  workflow_dispatch:  # Trigger the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and run tests
        run: mvn -f spring-boot-testing-main/pom.xml clean test

      - name: Display coverage information
        run: echo "Coverage is $COVERAGE%"

  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install dependencies
        run: mvn -f spring-boot-testing-main/pom.xml -B org.apache.maven.plugins:maven-dependency-plugin:3.1.2:get -Dartifact=org.jacoco:jacoco-maven-plugin:0.8.11 -DrepoUrl=https://repo.maven.apache.org/maven2/

      - name: Run JaCoCo for test coverage
        run: mvn -f spring-boot-testing-main/pom.xml jacoco:prepare-agent test jacoco:report

      - name: Check coverage threshold
        id: coverage
        run: |
          COVERAGE=$(grep -oP '<td class="ctr2">\s*([^<]+)\s*<\/td>' spring-boot-testing-main/target/site/jacoco/index.html | head -n 1 | grep -Po '<td class="ctr2">\K[^<]+')
          COVERAGE=${COVERAGE%\%}
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Error: Coverage is below 80%."
            exit 1
          fi

          echo "Coverage is $COVERAGE%"

      - name: Set coverage output in environment file
        run: echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV


      - name: Upload coverage results
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: spring-boot-testing-main/target/site/jacoco
